spring.application.name=Statify
spring.datasource.url=jdbc:mysql://localhost:3306/statify?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect.format_sql = true
spring.jpa.hibernate.ddl-auto=update
football.api.url=https://v3.football.api-sports.io
football.api.key=24f3a9bee3b339c0cc1d24a4e0dba847

scheduler.zone=Europe/Belgrade
scheduler.gg.cron=0 0 5 * * *
scheduler.fixture.cron=0 */30 * * * *