spring.application.name=Statify
spring.datasource.url=jdbc:mysql://localhost:3306/statify?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect.format_sql = true
spring.jpa.hibernate.ddl-auto=update
football.api.url=https://v3.football.api-sports.io
football.api.key=eb1df6a10c02c5e8cf95c849183a63a5
